### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by ousui** [wszgxa/hexo-theme-simple#1]
主题不错，很喜欢，很简约
自己做了修改，原本 800 宽太窄了
http://ousui.github.io

什么时候加入pjax就好了。

另外，为何我 tag， categaries 下都没有东西呢？

**Comment by wszgxa** [comment]
@ousui 因为还没开发完。等周六的时候完善下。tags和categories需要在source下面各创建一个文件夹tags,categories，然后放一个index.md里面的内容如下：

```
title: 标签
type: "tags"
comments: false
---
```

categories type是就是categories.

然后根目录下面的_config.yml需要有下面几行：

``` yml
tag_dir: tags
about_dir: about
archive_dir: archives
category_dir: categories
code_dir: downloads/code
```

那个800的宽度，是个人喜好。觉得应该专注于阅读。
